=== TimothyKodz/assignment-2--databases--cs-365--fall-2020/xml/dtd/student.dtd
<!ELEMENT student_registry (student+)>

<!ELEMENT student (contains)>
  <!ATTLIST student 
    id ID #REQUIRED>

<!ELEMENT contains (name, email+, phone_number+, student_info)>

<!ELEMENT name (preferred_name+)>
  <!ATTLIST name
    first CDATA #REQUIRED
    middle CDATA #REQUIRED
    last CDATA #REQUIRED>

<!ELEMENT preferred_name (#PCDATA)>

<!ELEMENT email (#PCDATA)>

<!ELEMENT phone_number (#PCDATA)>

<!ELEMENT student_info (year, gpa, major+, minor*, status, advisor+, graduation_date)>
  <!ATTLIST student_info
    date_enroll CDATA #REQUIRED>

<!ELEMENT status (#PCDATA)>
<!ELEMENT gpa (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT advisor (#PCDATA)>
<!ELEMENT graduation_date (#PCDATA)>

=== TimothyKodz/assignment-2--databases--cs-365--fall-2020/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE student_registry SYSTEM "dtd/student.dtd" [
    <!ENTITY like "">
    <!ENTITY dont-like "">
]

<?xml-stylesheet href="css/style.css"?>

<student_registry>
        <student id="">
          <personal_info>
            <name first="" middle="" last="">
              <preferred_name></preferred_name>
            </name>
            <email></email>
            <phone_number></phone_number>
          </personal_info>
          <student_info date_enroll="">
            <status></status>
            <gpa></gpa>
            <major></major>
            <minor></minor>
            <status></status>
            <advisor></advisor>
            <graduation_date></graduation_date>
          </student_info>
        </student>

</student_registry>
